version: '3.8'

# cmake -DBUILD_PYTHON_MODULE:BOOL=ON -DUSE_OPEN_MP:BOOL=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -S . -B ./build && \
# cmake --build ./build --target install --parallel $(nproc) 

services:
    build:
      build: .
      # working_dir: /home/build/Libraries/pointmatcher
      # volumes:
        # - ./:/home/build/Libraries/pointmatcher
    